apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 10s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/docker-desktop
  prune: true
  wait: true
  timeout: 10s
